### ISSUE TITLE
Construir diagrama de clases

### ISSUE THREAD

**Issue by SebasPelaez** [calidadudea/Arquitectura-y-Diseno#20]
Construir el diagrama de clases de la aplicación que permita modelar el comportamiento de los componentes que interactuan en ella.

- [x] Asignar responsbale.
- [x] Construir diagrama de clases.
- [x] Subir artefacto final.

**Comment by DavidAlejandroM** [comment]
[https://app.zenhub.com/files/197883041/321583d0-e03a-4391-9fe8-53f360574994/download](https://app.zenhub.com/files/197883041/321583d0-e03a-4391-9fe8-53f360574994/download)

Agregando artefacto

**Comment by DavidAlejandroM** [comment]
@andresr98 puedes revisar

**Comment by andresr98** [comment]
Se revisa diagrama y falta la multiplicidad

**Comment by DavidAlejandroM** [comment]
@andresr98 Revisado y corregido. [https://app.zenhub.com/files/197883041/d681eba2-20a6-434e-b9c8-ce2564e38786/download](https://app.zenhub.com/files/197883041/d681eba2-20a6-434e-b9c8-ce2564e38786/download)

**Comment by andresr98** [comment]
Se revisa diagrama y no se encuentran errores.
