### ISSUE TITLE
Epicas

### ISSUE THREAD

**Issue by randres-arcila** [calidadudea/Arquitectura-y-Diseno#8]
Volver issues la epicas

- [x] Definir una arquitectura que sea acorde a los requerimientos del proyecto.

- [x] Desarrollar el Frontend de la aplicación.

- [x] Hacer Diagramación.

![Epicas2](https://user-images.githubusercontent.com/42815710/61574484-03f15d00-aa86-11e9-8fe2-2f9748560bc1.png)

**Comment by SebasPelaez** [comment]
Se realizaron todas las actividades de este Issue, excepto la de construcción del frontend puesto que dicha tarea no corresponde al alcance asignado por el equipo.

**Comment by SebasPelaez** [comment]
Este Issue ya se puede cerrar. @andresr98

**Comment by andresr98** [comment]
Se encuentran documentos pertinentes para la épica.
